language: node_js

node_js:
  - 12

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        cleanup: false
        script:
          - npx semantic-release
